// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelToBase.Data;

namespace ModelToBase.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("ModelToBase.Data.Fromage", b =>
                {
                    b.Property<int>("idFromage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nomFromage")
                        .HasColumnType("text");

                    b.Property<double>("prixFromage")
                        .HasColumnType("double");

                    b.HasKey("idFromage");

                    b.ToTable("Fromage");
                });

            modelBuilder.Entity("ModelToBase.Data.Fruit", b =>
                {
                    b.Property<int>("idFruit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nomFruit")
                        .HasColumnType("text");

                    b.Property<double>("paysFruit")
                        .HasColumnType("double");

                    b.Property<double>("prixFruit")
                        .HasColumnType("double");

                    b.HasKey("idFruit");

                    b.ToTable("Fruit");
                });
#pragma warning restore 612, 618
        }
    }
}
