<!-- <nav>
<div><a href='?page=ListeAfpa_Anomalies'>Afpa_Anomalies</a></div>
<div><a href='?page=ListeAfpa_Cadences'>Afpa_Cadences</a></div>
<div><a href='?page=ListeAfpa_Couleurs'>Afpa_Couleurs</a></div>
<div><a href='?page=ListeAfpa_Erreurs'>Afpa_Erreurs</a></div>
<div><a href='?page=ListeAfpa_Lumieres'>Afpa_Lumieres</a></div>
<div><a href='?page=ListeAfpa_Objectifs'>Afpa_Objectifs</a></div>
<div><a href='?page=ListeAfpa_Seuils'>Afpa_Seuils</a></div>
<div><a href='?page=ListeAfpa_Sons'>Afpa_Sons</a></div>
<div><a href='?page=ListeAfpa_Temperatures'>Afpa_Temperatures</a></div>
<div><a href='?page=ListeUtilisateurs'>Utilisateurs</a></div>
</nav> -->